[preferred]
default=cosmic;gtk;

  
# Interface-specific overrides (e.g. wlroots for screencasting & screenshotting)
org.freedesktop.impl.portal.ScreenCast=wlr;cosmic;
org.freedesktop.impl.portal.Screenshot=wlr;cosmic;
